version: "3.8"

services:
  mysql:
    container_name: course-mysql-container
    image: mysql/mysql-server:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - mysql_course:/var/lib/mysql
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"

  api:
    container_name: course-api-container
    build:
      context: .
    image: node:20
    working_dir: /usr/src/course-manager-api
    restart: always
    env_file: ./.env
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    command: >
      sh -c "npm install --omit=dev && npm run start"
    ports:
      - "5052:5052"
    volumes:
      - ./dist:/usr/src/course-manager-api/dist/
      - ./package.json:/usr/src/course-manager-api/package.json
    depends_on:
      - mysql

volumes:
  mysql_course:
